{% set name = "fs_filepicker" %}
{% set version = "0.1.6" %}
{% set sha256 = "d1812a2c1fb8909de433a54c9960c51498759789e92b8bc40b462151b47a50a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ReimarBauer/fs_filepicker/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - fs_filepicker = fslib.fs_filepicker:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - pyqt 5.*
    - humanfriendly
    - fs
    - fs.webdavfs
    - fs.sshfs
    - future

test:
  imports:
    - fslib.fs_filepicker
  commands:
    - fs_filepicker -h

about:
  home: https://github.com/ReimarBauer/fs_filepicker
  license: APACHE 2.0
  license_file: LICENSE
  summary: 'QT file picker (Open|Save) for accessing a pyfilesystem2'
  dev_url: https://github.com/ReimarBauer/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
