{% set name = "fs_filepicker" %}
{% set version = "0.1.0" %}
{% set sha256 = "17124907ba269c402eaafbc5b3f35ec496ef1d1bf17bb1710e84bd1d71a86608" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ReimarBauer/fs_filepicker/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - fs_filepicker = fslib.fs_filepicker:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - pyqt 5.*
    - fs
    - fs.webdavfs
    - future

test:
  imports:
    - fslib.fs_filepicker
  commands:
    - fs_filepicker -h

about:
  home: https://github.com/ReimarBauer/fs_filepicker
  license: APACHE 2.0
  license_file: LICENSE
  summary: 'QT file picker (Open|Save) for accessing a pyfilesystem2'
  dev_url: https://github.com/ReimarBauer/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
