{% set name = "fs_filepicker" %}
{% set version = "0.0.3" %}
{% set sha256 = "ac0d7cd8fb064d108db08399dbf2600040f597b6c381398dceee92dd14cbd25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ReimarBauer/fs_filepicker/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - pyqt 5.*
    - fs
    - future

test:
  imports:
    - fslib.fs_filepicker

about:
  home: https://github.com/ReimarBauer/fs_filepicker
  license: APACHE 2.0
  license_file: LICENSE
  summary: 'QT file picker for accessing a pyfilesystem2'
  dev_url: https://github.com/ReimarBauer/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
