{% set name = "fs_filepicker" %}
{% set version = "0.0.6" %}
{% set sha256 = "9bb1ceb3743faa612b4002ea0894dc921df7396d7d8eba9daddf4777d7f5c993" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ReimarBauer/fs_filepicker/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - fs_filepicker = fslib.fs_filepicker:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - pyqt 5.*
    - fs
    - future

test:
  imports:
    - fslib.fs_filepicker
  commands:
    - fs_filepicker -h

about:
  home: https://github.com/ReimarBauer/fs_filepicker
  license: APACHE 2.0
  license_file: LICENSE
  summary: 'QT file picker (Open|Save) for accessing a pyfilesystem2'
  dev_url: https://github.com/ReimarBauer/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
