travis:
  secure:
    BINSTAR_TOKEN: fCE+nmsFQCXuP1uPM5DR5OQSmOM4JdDg6FIJOiHAUSMKTHqDIvbhk7E6Ks+q/vqmQipLSS1eydblm5Tgs8J0tVRc4qzAWzl17xMRd3Yae7QRleCHXLXDbNpe6xf1U9sH3P4EtvAj8s/sx4rclGaMlOFb7vGZnwjUP2igrS8vlopNRvvhfFCHfGd1zio00OLn3JMCu1IwTdqnteblkvzX/M18IosQ3YlnOzMgB+tGVoGeorS02+5TaievTsl3OHkhSMqzRNYdu7b9e0uvINv6+JvTBKWIS+tZVXjQXzR005jDXEPgr0CAA7/FA0pUG7H9qSj/7M2EN1Mn+aUEjmxV085+CTz/Cz35Xdi2ZyNy3BxuZBEF7UeJccbJsl1sIn+dZ1hTllvE/pAYuvBayxxmlZfx2bm1HA9z0IJ5Pgk8xgJ0e0wUPdgxc9stg8viPxs5wh6HrkWoqmLOVIYM3DKjKMFF/YbtdUeiKPbEmyF89BfWUwIOdEKR9HeXthj5vvffBbhXePLZNRDbrujUMJDIVqt4i8NSbzvnFNcZ7OML5VR/f6bcFSPGeEPynL2W3rljyxWYhgE32HtFhzLMaRTQc0ci1l5vnFfZoR/LBzXwQOY9i5NqWgbw5MO7ODWTeeTlQnkQcG9SbjEyGLkzzDYw/KtvggzoK/2O9TKX704ESes=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
